# Generated by Django 2.2.4 on 2019-08-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='joined',
            field=models.DateField(auto_now=True),
        ),
    ]
