# Generated by Django 2.2.4 on 2019-08-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190805_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='joined',
        ),
    ]
