@startuml
package common {
    class Subject {
        + UUID uuid
        ..Names..
        + Slug slug
        + String abbreviation
        + String name
        + CSSColor color
        ..Grades..
        + Float weight
        + Float goal
        ..Defaults..
        + String room
    }

    class User {
        + String username
        - Password password
        + Email email
        + Boolean is_superuser
        + Date joined
        + Date logged_in
        + IPAddress ip_address
    }
}
package Learn {
    class Note {
        + UUID uuid
        + String name
        ---
        + Text content
        + Path filepath
        + Date last_modified
    }

    class Learndata {
        + UUID uuid
        + Text data
        + Float learnt
    }
}

package Schedule {
    
    enum Weektype {
        Q1
        Q2
        BOTH
    }
    class Event {
        + UUID uuid
        + Time start
        + Time end
        + Integer day
        + Weektype week_type
        + Boolean deleted()
        + Event rescheduled()
    }
    
    class Mutation {
        + Date deleted
        + Boolean rescheduled()
        ..rescheduled() || null..
        + Date rescheduled
        + String room
        + Time rescheduled_start
        + Time rescheduled_end
    }
}

package Homework {
    class Grade {
        + UUID uuid
        + Date added
        + String name
        ..Values..
        + Float actual
        + Float expected
        + Float goal
        + Float maximum
        + Float weight
        ..Methods..
        + String name()
    }

    class Homework {
        + UUID uuid
        + String name
        + Text notes
        + Date due
        + Float progress()
        + Boolean is_test()
    }
}

User --> Subject

Subject --> Note
Subject --> Homework
Subject --> Event

Homework <--> "0..1" Grade
Note <--> "0..1" Learndata
Event <--> "0..*" Mutation
@enduml