@startuml
package common {
    class Subject {
        + UUID uuid
        ..Names..
        + Slug slug
        + String abbreviation
        + String name
        + CSSColor color
        ..Grades..
        + Float weight
        + Float goal
        ..Defaults..
        + String room
    }

    enum valueType {
        DATE
        TIME
        DATETIME
        TIMERANGE
        DATERANGE
        SELECT
        TEXT
        INTEGER
        FLOAT
        BOOLEAN
    }

    class SettingDefinition {
        ..Naming..
        String name
        String key
        String category
        String description
        ..Value definition..
        valueType type
        Boolean multiple
        String default
        Boolean optional
    }

    class Setting {
        String value
    }

    class User {
        + String username
        - Password password
        + Email email
        + Boolean is_superuser
        + Date joined
        + Date last_login
        + IPAddress ip_address
    }
}
package Learn {
    enum Filetype {
        MARKDOWN
        ASCIIDOC
        STUDENTML
    }

    class Note {
        + UUID uuid
        + String name
        ---
        + Text content
        + Path filetype
        + Date last_modified
        + Date created
        + Filetype filetype
    }

    class Learndata {
        + UUID uuid
        + Text data
        + Float progress
    }
}

package Schedule {
    
    enum Weektype {
        Q1
        Q2
        BOTH
    }
    class Event {
        + UUID uuid
        + Time start
        + Time end
        + Integer day
        + Weektype week_type
        + Boolean deleted()
        + Event rescheduled()
    }
    
    class Mutation {
        + Date deleted
        + Boolean rescheduled()
        ..rescheduled() || null..
        + Date rescheduled
        + String room
        + Time rescheduled_start
        + Time rescheduled_end
    }
}

package Homework {
    class Grade {
        + UUID uuid
        + Date added
        + String name
        ..Values..
        + Float actual
        + Float expected
        + Float goal
        + Float maximum
        + Float weight
        ..Methods..
        + String name()
    }

    class Homework {
        + UUID uuid
        + String name
        + Text notes
        + Date due
        + Float progress()
        + Boolean is_test()
    }
}

User --> Subject
User --> Setting
SettingDefinition --> Setting

Subject --> Note
Subject --> Homework
Subject --> Event
Subject --> Learndata
Subject --> Grade

Note <--> "0..*" Learndata
Homework <--> "0..*" Grade
Event <--> "0..*" Mutation
@enduml