# Generated by Django 2.2.4 on 2019-08-05 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.TextField()),
                ('default', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('#(?:[A-Fa-f0-9]{3}){1,2}', 'Please use a valid hexadecimal color format, eg. #268CCE, or #FFF')])),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('abbreviation', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('[\\w_\\-]{3}Please use exactly 3 alphanumeric characters (- and _ are also accepted)')])),
            ],
        ),
    ]
