# Generated by Django 2.2.4 on 2019-08-05 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20190805_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='abbreviation',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('[a-zA-Z_\\-]{3}Please use exactly 3 letters (- and _ are also accepted)')]),
        ),
    ]
