# Generated by Django 2.2.6 on 2019-10-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20191011_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultsetting',
            name='multiple',
            field=models.BooleanField(default=False),
        ),
    ]
