# Generated by Django 2.2.6 on 2019-10-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_defaultsetting_multiple'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='logged_in',
        ),
    ]
