# Generated by Django 2.2.4 on 2019-08-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20190805_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='abbreviation',
            field=models.CharField(max_length=3),
        ),
    ]
