# Generated by Django 2.2.4 on 2019-08-05 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20190805_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='key',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='subject',
            name='abbreviation',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('[a-z_\\-]{3}', 'Please use exactly 3 lower-case letters (- and _ are also accepted)')]),
        ),
    ]
