# Generated by Django 2.2.4 on 2019-08-05 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20190805_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='default',
        ),
    ]
