# Generated by Django 2.2.6 on 2019-10-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('common', '0007_auto_20191011_2155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefaultSetting',
            new_name='SettingDefition',
        ),
    ]
