# Generated by Django 2.2.6 on 2019-12-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_auto_20191016_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='abbreviation',
        ),
        migrations.AlterField(
            model_name='settingdefinition',
            name='category',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
