# Generated by Django 2.2.4 on 2019-08-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_setting_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='room',
        ),
        migrations.AddField(
            model_name='subject',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
