# Generated by Django 2.2.6 on 2019-12-08 17:57

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20191208_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name']),
        ),
    ]
