# Generated by Django 2.2.4 on 2019-08-18 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20190818_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='abbreviation',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('[a-z_\\-]{3}', 'Please use exactly 3 lower-case letters (- and _ are also accepted)')]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
