# Generated by Django 2.2.6 on 2019-12-21 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20191208_1757'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='setting',
            unique_together={('user', 'setting')},
        ),
    ]
