# Generated by Django 2.2.4 on 2019-08-18 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20190818_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grade_goal',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, "This can't be a negative value"), django.core.validators.MaxValueValidator(1, 'This should be a value between 0 and 1')]),
        ),
        migrations.AddField(
            model_name='subject',
            name='physical_weight',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, "This can't be a negative value")]),
        ),
    ]
