# Generated by Django 2.2.4 on 2019-08-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_auto_20190818_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='room',
            field=models.CharField(default='LOL69', max_length=100),
            preserve_default=False,
        ),
    ]
