# Generated by Django 2.2.4 on 2019-08-22 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20190822_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('namespace', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('datetime', 'Date & heure'), ('date', 'Date'), ('dates', 'Dates'), ('daterange', 'Plage de dates'), ('dateranges', 'Plages de dates'), ('time', 'Heure'), ('times', 'Heures'), ('timerange', 'Plage horaire'), ('timeranges', 'Plages horaires'), ('choices', 'Choix'), ('text', 'Texte'), ('posint', 'Nombre entier positif'), ('int', 'Nombre entier'), ('float', 'Nombre décimal'), ('posfloat', 'Nombre décimal positif')], default='text', max_length=12)),
                ('choices', models.TextField(blank=True, null=True)),
                ('default', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='setting',
            name='name',
        ),
        migrations.AlterField(
            model_name='subject',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='setting',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.DefaultSetting', to_field='key'),
            preserve_default=False,
        ),
    ]
