# Generated by Django 2.2.8 on 2020-01-18 12:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20200106_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Début')),
                ('end', models.DateField(verbose_name='Fin')),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_start', models.DateField(blank=True, null=True, verbose_name='Rentrée')),
                ('trimester_2_start', models.DateField(blank=True, null=True, verbose_name='Début du second trimestre')),
                ('trimester_3_start', models.DateField(blank=True, null=True, verbose_name='Début du troisième trimestre')),
                ('year_end', models.DateField(blank=True, null=True, verbose_name="Fin de l'année scolaire")),
                ('theme', models.CharField(choices=[('LIGHT', 'Clair'), ('DARK', 'Sombre'), ('AUTO', 'Automatique')], default='AUTO', max_length=50)),
                ('show_completed_exercises', models.BooleanField(default=False, verbose_name='Afficher les exercices complétés')),
                ('grades_unit', models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Unité des notes')),
                ('grades_default_weight', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Coefficient par défaut')),
                ('use_schedule', models.BooleanField(default=True, verbose_name="Utiliser l'emploi du temps")),
            ],
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
        migrations.DeleteModel(
            name='SettingDefinition',
        ),
        migrations.AddField(
            model_name='offday',
            name='user_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offdays', to='common.UserSettings'),
        ),
        migrations.AddField(
            model_name='user',
            name='settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.UserSettings'),
        ),
    ]
