# Generated by Django 2.2.4 on 2019-08-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_auto_20190822_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultsetting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defaultsetting',
            name='default',
            field=models.TextField(blank=True, null=True),
        ),
    ]
