# Generated by Django 2.2.4 on 2019-08-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_auto_20190822_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultsetting',
            name='blank',
            field=models.BooleanField(default=False),
        ),
    ]
