# Generated by Django 2.2.4 on 2019-08-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_defaultsetting_blank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultsetting',
            old_name='blank',
            new_name='required',
        ),
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
