# Generated by Django 2.2.4 on 2019-08-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_auto_20190823_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultsetting',
            name='kind',
            field=models.CharField(choices=[('datetime', 'Date & heure'), ('date', 'Date'), ('dates', 'Dates'), ('daterange', 'Plage de dates'), ('dateranges', 'Plages de dates'), ('time', 'Heure'), ('times', 'Heures'), ('timerange', 'Plage horaire'), ('timeranges', 'Plages horaires'), ('choices', 'Choix'), ('text', 'Texte'), ('posint', 'Nombre entier positif'), ('int', 'Nombre entier'), ('float', 'Nombre décimal'), ('posfloat', 'Nombre décimal positif'), ('boolean', 'Booléen (oui/non)')], default='text', max_length=12),
        ),
    ]
