# Generated by Django 2.2.4 on 2019-08-31 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_auto_20190831_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.DefaultSetting'),
        ),
    ]
