# Generated by Django 2.2.4 on 2019-10-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_auto_20190831_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grade_weight',
            field=models.FloatField(default=1),
        ),
    ]
