# Generated by Django 2.2.4 on 2019-10-07 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_subject_grade_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='grade_weight',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0, "This can't be a negative value")]),
        ),
    ]
