# Generated by Django 2.2.8 on 2020-01-13 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='by_email',
        ),
        migrations.AlterField(
            model_name='report',
            name='browser',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='device',
            field=models.CharField(choices=[('PHONE', 'Smartphone'), ('TABLET', 'Tablette'), ('LAPTOP', 'Ordinateur portable'), ('DESKTOP', 'Ordinateur fixe'), ('SMARTWATCH', 'Montre connectée'), ('OTHER', 'Autre')], default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='os',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='screen_size',
            field=models.CharField(default='Unknown', max_length=200, validators=[django.core.validators.RegexValidator('(?:Unknown)|(?:(\\d+)x(\\d+))')]),
        ),
        migrations.AlterField(
            model_name='report',
            name='url',
            field=models.URLField(default='Unknown'),
        ),
    ]
