# Generated by Django 2.2.8 on 2020-01-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200113_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
