# Generated by Django 2.2.8 on 2020-02-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
