# Generated by Django 2.2.6 on 2019-10-10 19:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('room', models.CharField(max_length=300)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=9)),
                ('week_type', models.CharField(choices=[('both', 'Both'), ('Q1', 'Q1'), ('Q2', 'Q2')], default=('both', 'Both'), max_length=4)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='common.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Mutation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('deleted', models.DateField()),
                ('rescheduled', models.DateField(blank=True, null=True)),
                ('start', models.TimeField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True)),
                ('room', models.CharField(blank=True, max_length=300, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutations', to='schedule.Event')),
            ],
        ),
    ]
