# Generated by Django 2.2.4 on 2019-08-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='<whatever>', max_length=400),
            preserve_default=False,
        ),
    ]
