# Generated by Django 2.2.6 on 2019-10-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=9),
        ),
        migrations.AlterField(
            model_name='event',
            name='week_type',
            field=models.CharField(choices=[('BOTH', 'Both'), ('Q1', 'Q1'), ('Q2', 'Q2')], default=('BOTH', 'Both'), max_length=4),
        ),
    ]
