# Generated by Django 2.2.4 on 2019-08-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_exercise_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='week_type',
            new_name='weekType',
        ),
    ]
