# Generated by Django 2.2.6 on 2019-10-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20191011_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutation',
            name='deleted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
