# Generated by Django 2.2.4 on 2019-08-05 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20190805_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletion',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deletion', to='schedule.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=9),
        ),
    ]
