# Generated by Django 2.2.6 on 2019-11-07 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_auto_20191016_1600'),
        ('schedule', '0004_auto_20191011_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutation',
            name='end',
        ),
        migrations.RemoveField(
            model_name='mutation',
            name='rescheduled',
        ),
        migrations.RemoveField(
            model_name='mutation',
            name='start',
        ),
        migrations.AddField(
            model_name='mutation',
            name='rescheduled_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mutation',
            name='rescheduled_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mutation',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='mutations', to='common.Subject'),
            preserve_default=False,
        ),
    ]
