# Generated by Django 2.2.4 on 2019-08-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20190805_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='weekType',
            field=models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('both', 'Both')], max_length=4),
        ),
    ]
