# Generated by Django 2.2.4 on 2019-08-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20190814_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addition',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
