# Generated by Django 2.2.4 on 2019-08-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20190814_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='weekType',
            field=models.CharField(choices=[('both', 'Both'), ('Q1', 'Q1'), ('Q2', 'Q2')], default=('both', 'Both'), max_length=4),
        ),
    ]
