# Generated by Django 2.2.4 on 2019-08-17 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_auto_20190816_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='weekType',
            new_name='week_type',
        ),
    ]
