# Generated by Django 2.2.4 on 2019-08-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_auto_20190821_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='room',
            field=models.CharField(default='L69', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addition',
            name='room',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='room',
            field=models.CharField(max_length=100),
        ),
    ]
