# Generated by Django 2.2.4 on 2019-08-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20190822_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='due',
            field=models.DateField(),
        ),
    ]
