# Generated by Django 2.2.4 on 2019-08-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_UUIDs_on_all_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='uuid',
        ),
    ]
