# Generated by Django 2.2.6 on 2019-10-11 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_homework_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='progress',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, "This can't be a negative value"), django.core.validators.MaxValueValidator(1, 'This should be a value between 0 and 1')]),
        ),
    ]
