# Generated by Django 2.2.6 on 2019-10-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_homework_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='is_test',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
