# Generated by Django 2.2.6 on 2019-10-29 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_homework_is_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='is_test',
        ),
    ]
