# Generated by Django 2.2.6 on 2019-10-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0006_remove_homework_is_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='type',
            field=models.CharField(choices=[('TEST', 'Contrôle'), ('DM', 'Devoir maison'), ('EXERCISE', 'Exercice'), ('TOBRING', 'À apporter')], default='EXERCISE', max_length=2, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
