# Generated by Django 2.2.6 on 2019-11-07 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0007_homework_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='created',
            new_name='added',
        ),
        migrations.AddField(
            model_name='grade',
            name='date_obtained',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='unit',
            field=models.FloatField(default=20, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Grade unit'),
        ),
    ]
