# Generated by Django 2.2.6 on 2019-12-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0008_auto_20191107_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='completed',
        ),
    ]
