# Generated by Django 2.2.6 on 2019-12-09 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0009_auto_20191208_1520'),
        ('homework', '0009_remove_homework_completed'),
    ]

    operations = [
    ]
