# Generated by Django 2.2.6 on 2019-12-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0010_merge_20191209_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
