# Generated by Django 2.2.6 on 2019-12-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0011_homework_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='notes',
        ),
        migrations.AddField(
            model_name='homework',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
