# Generated by Django 2.2.6 on 2019-12-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0014_auto_20191219_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='grades',
            field=models.ManyToManyField(blank=True, to='homework.Grade'),
        ),
    ]
