# Generated by Django 2.2.6 on 2019-12-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0015_auto_20191219_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='type',
            field=models.CharField(choices=[('TEST', 'Contrôle'), ('COURSEWORK', 'Devoir maison'), ('EXERCISE', 'Exercice'), ('TOBRING', 'À apporter')], max_length=10, verbose_name='Type'),
        ),
    ]
