# Generated by Django 2.2.8 on 2020-02-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0017_auto_20191228_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='added',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
