# Generated by Django 2.2.4 on 2019-08-05 15:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
                ('progress', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, "The progress can't be a negative value"), django.core.validators.MaxValueValidator(1, 'The progress should be a value between 0 and 1')])),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notions', to='common.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('room', models.CharField(max_length=10)),
                ('notes', models.TextField()),
                ('notion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='learn.Notion')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastModified', models.DateTimeField()),
                ('notion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='learn.Notion')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual', models.FloatField(validators=[django.core.validators.MinValueValidator(0, "The progress can't be a negative value"), django.core.validators.MaxValueValidator(1, 'The progress should be a value between 0 and 1')])),
                ('expected', models.FloatField(validators=[django.core.validators.MinValueValidator(0, "The progress can't be a negative value"), django.core.validators.MaxValueValidator(1, 'The progress should be a value between 0 and 1')])),
                ('goal', models.FloatField(validators=[django.core.validators.MinValueValidator(0, "The progress can't be a negative value"), django.core.validators.MaxValueValidator(1, 'The progress should be a value between 0 and 1')])),
                ('weight', models.FloatField()),
                ('maximum', models.FloatField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='learn.Test')),
            ],
        ),
    ]
