# Generated by Django 2.2.4 on 2019-08-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='test',
            name='notion',
        ),
        migrations.AddField(
            model_name='test',
            name='notions',
            field=models.ManyToManyField(to='learn.Notion'),
        ),
    ]
