# Generated by Django 2.2.6 on 2019-10-11 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='filetype',
            new_name='format',
        ),
    ]
