# Generated by Django 2.2.6 on 2019-10-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20191011_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='learndata',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
