# Generated by Django 2.2.4 on 2019-08-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20190805_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notion',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='test',
            name='notions',
            field=models.ManyToManyField(related_name='tests', to='learn.Notion'),
        ),
    ]
