# Generated by Django 2.2.4 on 2019-08-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20190805_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='filepath',
            field=models.FilePathField(default='lol'),
            preserve_default=False,
        ),
    ]
