# Generated by Django 2.2.6 on 2019-10-11 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_learndata_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learndata',
            old_name='learnt',
            new_name='progress',
        ),
    ]
