# Generated by Django 2.2.6 on 2019-10-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_auto_20191011_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learndata',
            old_name='created',
            new_name='added',
        ),
        migrations.RenameField(
            model_name='learndata',
            old_name='last_opened',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='last_modified',
            new_name='modified',
        ),
        migrations.AddField(
            model_name='learndata',
            name='opened',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='note',
            name='added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='note',
            name='opened',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
