# Generated by Django 2.2.6 on 2019-10-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_auto_20191015_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learndata',
            name='note',
        ),
        migrations.AddField(
            model_name='learndata',
            name='notes',
            field=models.ManyToManyField(to='learn.Note'),
        ),
    ]
