# Generated by Django 2.2.4 on 2019-08-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_auto_20190814_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='notion',
        ),
        migrations.AddField(
            model_name='note',
            name='notion',
            field=models.ManyToManyField(related_name='notes', to='learn.Notion'),
        ),
    ]
