# Generated by Django 2.2.6 on 2019-10-29 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_auto_20191016_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learndata',
            name='notes',
        ),
    ]
