# Generated by Django 2.2.6 on 2019-12-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_remove_learndata_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created',
        ),
        migrations.AddField(
            model_name='learndata',
            name='notes',
            field=models.ManyToManyField(to='learn.Note'),
        ),
        migrations.AlterField(
            model_name='learndata',
            name='data',
            field=models.TextField(blank=True, null=True, verbose_name='JSON/YAML Content'),
        ),
        migrations.AlterField(
            model_name='learndata',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='format',
            field=models.CharField(choices=[('MARKDOWN', 'Markdown'), ('ASCIIDOC', 'AsciiDoc'), ('STUDENTML', 'StudentML'), ('HTML', 'HTML')], default=('MARKDOWN', 'Markdown'), max_length=50),
        ),
    ]
