# Generated by Django 2.2.4 on 2019-08-17 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_grade_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='lastModified',
            new_name='last_modified',
        ),
    ]
