# Generated by Django 2.2.4 on 2019-08-18 12:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20190806_2030'),
        ('learn', '0009_auto_20190817_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='notion',
        ),
        migrations.RemoveField(
            model_name='test',
            name='notions',
        ),
        migrations.AddField(
            model_name='note',
            name='learnt',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, "This can't be a negative value"), django.core.validators.MaxValueValidator(1, 'This should be a value between 0 and 1')]),
        ),
        migrations.AddField(
            model_name='note',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='common.Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='filepath',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.DeleteModel(
            name='Notion',
        ),
    ]
