# Generated by Django 2.2.6 on 2019-12-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_auto_20191208_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='format',
            field=models.CharField(choices=[('MARKDOWN', 'Markdown'), ('ASCIIDOC', 'AsciiDoc'), ('STUDENTML', 'StudentML'), ('HTML', 'HTML'), ('LINK', 'Application externe')], default=('MARKDOWN', 'Markdown'), max_length=50),
        ),
    ]
