# Generated by Django 2.2.6 on 2019-12-28 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0010_auto_20191214_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learndata',
            name='progress',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, "This can't be a negative value"), django.core.validators.MaxValueValidator(1, "This can't be greater than 1")], verbose_name='Learning progress'),
        ),
    ]
