# Generated by Django 2.2.4 on 2019-08-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0010_auto_20190818_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='filepath',
            field=models.CharField(max_length=1000),
        ),
    ]
