# Generated by Django 2.2.4 on 2019-08-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0011_auto_20190818_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
