# Generated by Django 2.2.4 on 2019-08-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0012_auto_20190818_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='test',
            name='notes',
        ),
        migrations.AddField(
            model_name='test',
            name='notes',
            field=models.ManyToManyField(related_name='tests', to='learn.Note'),
        ),
    ]
