# Generated by Django 2.2.4 on 2019-08-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0013_auto_20190821_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='filepath',
        ),
    ]
