# Generated by Django 2.2.4 on 2019-08-22 09:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0014_remove_note_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
    ]
