# Generated by Django 2.2.4 on 2019-08-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0016_auto_20190822_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='room',
            field=models.CharField(max_length=100),
        ),
    ]
