# Generated by Django 2.2.4 on 2019-08-22 12:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0016_auto_20190822_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='test',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='test',
            name='room',
            field=models.CharField(max_length=100),
        ),
    ]
