# Generated by Django 2.2.4 on 2019-08-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0020_auto_20190823_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='filetype',
            field=models.CharField(default='markdown', max_length=50),
        ),
    ]
