# Generated by Django 2.2.4 on 2019-09-08 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0022_test_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='learnt',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, "This can't be a negative value"), django.core.validators.MaxValueValidator(1, 'This should be a value between 0 and 1')]),
        ),
    ]
